name: Build and Push to ACR

on:
  workflow_dispatch:  # Isse tum manually GitHub se trigger kar sakte ho

permissions:
  id-token: write
  contents: read
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: todo-ui
      IMAGE_TAG: v4
      ACR_NAME: rupeshcr
      ACR_LOGIN_SERVER: rupeshcr.azurecr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 76f058d4-660c-4f0e-a458-36a0f2c022f8
          tenant-id: b1f59b76-a82c-426c-9731-9511e3224ea1
          subscription-id: 76d1a5ca-14a0-499c-9bf4-5ad4a778539f

      - name: Log in to ACR
        run: |
          az acr login --name $ACR_NAME

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Tag Docker Image for ACR
        run: |
          docker tag $IMAGE_NAME:$IMAGE_TAG $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG

      - name: Push Docker Image to ACR
        run: |
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
